org: shopwallet
app: shop-wallet-serverless
service: shop-wallet-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  profile: ${opt:stage, "dev"}
  environment:
    user_pool_id:
      Ref: UserPool
    client_id:
      Ref: UserClient
    dynamo_table:
      Ref: MainTable
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:AdminInitiateAuth
        - cognito-idp:AdminRespondToAuthChallenge
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminSetUserPassword
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:Scan
        - dynamodb:BatchGetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:RemoveItem
        - sns:*
      Resource: '*'

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-prune-plugin
  - serverless-middleware

custom:
  prune:
    automatic: true
    number: 5
  userPoolName: shop-wallet-users-pool-${self:provider.profile}
  customDomain:
    domainName: ${opt:stage}-api.shopwalletapp.com
    basePath: 'api'
    stage: ${opt:stage}
    createRoute53Record: true

functions:
  makeTransaction:
    handler: build/src/endpoints/transactions/makeTransaction.makeTransaction
    middleware:
      pre:
        - build/src/middlewares/authorization.authorization
    events:
      - http:
          path: /v1/transaction
          method: post
          cors: true

  getTransactionByAdmin:
    handler: build/src/endpoints/transactions/getTransactionByAdmin.getTransactions
    middleware:
      pre:
        - build/src/middlewares/authorization.authorization
    events:
      - http:
          path: /v1/transactions
          method: get
          cors: true

  getTransactions:
    handler: build/src/endpoints/transactions/getTransactions.getTransactions
    middleware:
      pre:
        - build/src/middlewares/authorization.authorization
    events:
      - http:
          path: /v1/transactions/{phoneNumber}
          method: get
          cors: true

  getTransactionsRoom:
    handler: build/src/endpoints/transactions/getTransactionsRoom.getTransactionsRoom
    middleware:
      pre:
        - build/src/middlewares/authorization.authorization
    events:
      - http:
          path: /v1/transactions/room
          method: post
          cors: true

  getUser:
    handler: build/src/endpoints/user/getUser.getUser
    middleware:
      pre:
        - build/src/middlewares/authorization.authorization
    events:
      - http:
          path: /v1/users/{phoneNumber}
          method: get
          cors: true

  getRegisteredUsers:
    handler: build/src/endpoints/user/getRegisteredUsers.getRegisteredUsers
    middleware:
      pre:
        - build/src/middlewares/authorization.authorization
    events:
      - http:
          path: /v1/users/registered
          method: post
          cors: true
  signIn:
    timeout: 10
    handler: build/src/endpoints/sign-in/sign-in.signIn
    events:
      - http:
          path: /v1/auth/sign-in
          method: post
          cors: true

  signInVerify:
    timeout: 10
    handler: build/src/endpoints/sign-in-verify/sign-in-verify.signInVerify
    events:
      - http:
          path: /v1/auth/sign-in/verify
          method: post
          cors: true

  refreshToken:
    timeout: 10
    handler: build/src/endpoints/refreshToken/refreshToken.refreshTokenHandler
    events:
      - http:
          path: /v1/auth/refreshToken
          method: post
          cors: true

resources:
  Resources:
    MainTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MainTable-${self:provider.profile}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
