org: shopwallet
app: shop-wallet-serverless
service: shop-wallet-serverless

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  profile: ${opt:stage, "dev"}
  versionFunctions: false
  environment:
    stage: ${opt:stage}
    MAIN_TABLE:
      Ref: MainTable
    MAIN_QUEUE_URL:
      Ref: MainQueue
    EXAMPLE: ${env:EXAMPLE}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:Scan
        - dynamodb:BatchGetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:RemoveItem
        - dynamodb:DeleteItem
        - sns:*
        - sqs:*
        - s3:*
      Resource: '*'

plugins:
  - serverless-offline
  - serverless-certificate-creator
  - serverless-domain-manager
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 5

functions:
  ping:
    handler: build/src/endpoints/github/createRepositoryFromTemplate.main
    events:
      - http:
          path: /v1/ping
          method: GET
          cors: true
resources:
  Resources:
    MainQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: MainQueue-${self:provider.profile}
        VisibilityTimeout: 60
    MainTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MainTable-${self:provider.profile}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI1PK
            AttributeType: S
          - AttributeName: GSI1SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: GSI1PK
                KeyType: HASH
              - AttributeName: GSI1SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
    MainBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: main-bucket-${self:provider.profile}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
        OwnershipControls:
          Rules:
            - ObjectOwnership: ObjectWriter
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000
