org: shopwallet
app: shop-wallet-serverless
service: shop-wallet-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  profile: ${opt:stage, "dev"}
  environment:
    stage: ${opt:stage}
    dynamo_table:
      Ref: MainTable
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:Scan
        - dynamodb:BatchGetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:RemoveItem
        - dynamodb:DeleteItem
        - sns:*
      Resource: '*'

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 5
  customDomain:
    domainName: ${opt:stage}-api.shopwalletapp.com
    basePath: 'api'
    stage: ${opt:stage}
    createRoute53Record: true

functions:
  getUserWallet:
    handler: build/src/endpoints/user/getUserWallet.getUserWallet
    events:
      - http:
          path: /v1/user/wallet
          method: post
          cors: true
  setStoreValues:
    handler: build/src/endpoints/store/setStoreValues.setStoreValues
    events:
      - http:
          path: /v1/store/set-store-values
          method: post
          cors: true
  getStoreValuesForAdmin:
    handler: build/src/endpoints/store/getStoreValuesForAdmin.getStoreValuesForAdmin
    events:
      - http:
          path: /v1/store/get-store-values-for-admin
          method: post
          cors: true
  getUsersForAdmin:
    handler: build/src/endpoints/user/getUsersForAdmin.getUsersForAdmin
    events:
      - http:
          path: /v1/users/get-users-for-admin
          method: post
          cors: true
  withdraw:
    handler: build/src/endpoints/wallet/withdraw.withdraw
    events:
      - http:
          path: /v1/wallet/withdraw
          method: post
          cors: true

  deposit:
    handler: build/src/endpoints/wallet/deposit.deposit
    events:
      - http:
          path: /v1/wallet/deposit
          method: post
          cors: true

  usersWalletAddresses:
    handler: build/src/endpoints/store/usersWalletAddresses.usersWalletAddresses
    events:
      - http:
          path: /v1/store/usersWalletAddresses
          method: post
          cors: true

  withdrawSuccess:
    handler: build/src/endpoints/store/withdrawSuccess.withdrawSuccess
    events:
      - http:
          path: /v1/store/withdrawSuccess
          method: post
          cors: true

  savePushTokenToUser:
    handler: build/src/endpoints/savePushTokenToUser/savePushTokenToUser.savePushTokenToUser
    events:
      - http:
          path: /v1/users/pushToken
          method: post
          cors: true

  makeTransaction:
    handler: build/src/endpoints/transactions/makeTransaction.makeTransaction
    events:
      - http:
          path: /v1/transaction
          method: post
          cors: true

  getTransactions:
    handler: build/src/endpoints/transactions/getTransactions.getTransactions
    events:
      - http:
          path: /v1/transactions/{phoneNumber}
          method: get
          cors: true

  getTransactionsRoom:
    handler: build/src/endpoints/transactions/getTransactionsRoom.getTransactionsRoom
    events:
      - http:
          path: /v1/transactions/room
          method: post
          cors: true

  getUser:
    handler: build/src/endpoints/user/getUser.getUser
    events:
      - http:
          path: /v1/users/{phoneNumber}
          method: get
          cors: true
  getRegisteredUsers:
    handler: build/src/endpoints/user/getRegisteredUsers.getRegisteredUsers
    events:
      - http:
          path: /v1/users/registered
          method: post
  updateUser:
    handler: build/src/endpoints/user/updateUser.updateUser
    events:
      - http:
          path: /v1/users/update
          method: put
          cors: true

  signIn:
    handler: build/src/endpoints/sign-in/sign-in.signIn
    events:
      - http:
          path: /v1/auth/sign-in
          method: post
          cors: true

  signInVerify:
    handler: build/src/endpoints/sign-in-verify/sign-in-verify.signInVerify
    events:
      - http:
          path: /v1/auth/sign-in/verify
          method: post
          cors: true

  refreshToken:
    handler: build/src/endpoints/refreshToken/refreshToken.refreshTokenHandler
    events:
      - http:
          path: /v1/auth/refreshToken
          method: post
          cors: true

  createFeedback:
    handler: build/src/endpoints/feedback/createFeedback.createFeedback
    events:
      - http:
          path: /v1/feedback
          method: post
          cors: true

resources:
  Resources:
    MainTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MainTable-${self:provider.profile}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI1PK
            AttributeType: S
          - AttributeName: GSI1SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: GSI1PK
                KeyType: HASH
              - AttributeName: GSI1SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
