org: shopwallet
app: shop-wallet-serverless
service: shop-wallet-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  profile: ${opt:stage, "dev"}
  environment:
    user_pool_id:
      Ref: UserPool
    client_id:
      Ref: UserClient
    dynamo_table:
      Ref: UsersTable
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:AdminInitiateAuth
        - cognito-idp:AdminRespondToAuthChallenge
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminSetUserPassword
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - sns:*
      Resource: '*'

plugins:
  - serverless-offline

functions:
  signUp:
    handler: build/src/endpoints/sign-up/sign-up.signUp
    events:
      - http:
          path: /api/shop-wallet/auth/sign-up
          method: post
          cors: true
  signIn:
    handler: build/src/endpoints/sign-in/sign-in.signIn
    events:
      - http:
          path: /api/shop-wallet/auth/sign-in
          method: post
          cors: true
  createAuthChallenge:
    handler: build/src/triggers/create-auth-challenge.createAuthChallenge
    events:
      - cognitoUserPool:
          pool: UserPool
          trigger: CreateAuthChallenge
  verifyAuthChallenge:
    handler: build/src/triggers/verify-auth-challenge.verifyAuthChallenge
    events:
      - cognitoUserPool:
          pool: UserPool
          trigger: VerifyAuthChallengeResponse
  defineAuthChallenge:
    handler: build/src/triggers/define-auth-challenge.defineAuthChallenge
    events:
      - cognitoUserPool:
          pool: UserPool
          trigger: DefineAuthChallenge
  preSignUp:
    handler: build/src/triggers/pre-sign-up.preSignUp
    events:
      - cognitoUserPool:
          pool: UserPool
          trigger: PreSignUp

resources:
  Resources:
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: shop-wallet-users-pool-${self:provider.profile}
        UsernameAttributes:
          - phone_number
        Policies:
          PasswordPolicy:
            RequireLowercase: false
            RequireSymbols: false
            RequireNumbers: false
            MinimumLength: 6
            RequireUppercase: false
    UserClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: shop-wallet-app-client-${self:provider.profile}
        GenerateSecret: false
        UserPoolId:
          Ref: UserPool
        ExplicitAuthFlows:
          - 'ALLOW_CUSTOM_AUTH'
          - 'ALLOW_REFRESH_TOKEN_AUTH'

    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UsersTable-${self:provider.profile}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S

        KeySchema:
          - AttributeName: id
            KeyType: HASH

        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
