name: CI-CD
on:
  push:
    branches: [staging]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      ALCHEMY_API_KEY_MATIC: ${{ secrets.ALCHEMY_API_KEY_MATIC }}
      ALCHEMY_API_KEY_ETH: ${{ secrets.ALCHEMY_API_KEY_ETH }}
      CHAINSTACK_NODE: ${{ vars.CHAINSTACK_NODE }}
      TATUM_WEBHOOK_URL: ${{ secrets.TATUM_WEBHOOK_URL }}
      TATUM_API_KEY: ${{ secrets.TATUM_API_KEY }}
      ETHERSCAN_API_KEY: ${{ vars.ETHERSCAN_API_KEY }}
      POLYGONSCAN_API_KEY: ${{ vars.POLYGONSCAN_API_KEY }}
      COIN_MARKET_CAP_API_KEY: ${{ vars.COIN_MARKET_CAP_API_KEY }}
      COIN_MARKET_CAP_API_URL: ${{ vars.COIN_MARKET_CAP_API_URL }}
      STAGING_SLACK_SUPPORT_URL: ${{ secrets.STAGING_SLACK_SUPPORT_URL }}
      STAGING_SLACK_FEEDBACK_URL: ${{ secrets.STAGING_SLACK_FEEDBACK_URL }}
      STAGING_SLACK_GET_BALANCES_URL: ${{ secrets.STAGING_SLACK_GET_BALANCES_URL }}
      STAGING_SLACK_GET_TRANSACTION_URL: ${{ secrets.STAGING_SLACK_GET_TRANSACTION_URL }}
      STAGING_SLACK_MAKE_TRANSACTION_URL: ${{ secrets.STAGING_SLACK_MAKE_TRANSACTION_URL }}
      STAGING_SLACK_UPDATE_PRICES_URL: ${{ secrets.STAGING_SLACK_UPDATE_PRICES_URL }}
      STAGING_SLACK_CREATE_WALLET_URL: ${{ secrets.STAGING_SLACK_CREATE_WALLET_URL }}
      STAGING_SLACK_MONITORING_URL: ${{ secrets.STAGING_SLACK_MONITORING_URL }}
      PROD_SLACK_SUPPORT_URL: ${{ secrets.PROD_SLACK_SUPPORT_URL }}
      PROD_SLACK_FEEDBACK_URL: ${{ secrets.PROD_SLACK_FEEDBACK_URL }}
      PROD_SLACK_GET_BALANCES_URL: ${{ secrets.PROD_SLACK_GET_BALANCES_URL }}
      PROD_SLACK_GET_TRANSACTION_URL: ${{ secrets.PROD_SLACK_GET_TRANSACTION_URL }}
      PROD_SLACK_MAKE_TRANSACTION_URL: ${{ secrets.PROD_SLACK_MAKE_TRANSACTION_URL }}
      PROD_SLACK_UPDATE_PRICES_URL: ${{ secrets.PROD_SLACK_UPDATE_PRICES_URL }}
      PROD_SLACK_CREATE_WALLET_URL: ${{ secrets.PROD_SLACK_CREATE_WALLET_URL }}
      PROD_SLACK_MONITORING_URL: ${{ secrets.PROD_SLACK_MONITORING_URL }}
      TELEGRAM_BOT_TOKEN: ${{ vars.STAGING_TELEGRAM_BOT_TOKEN }}
      SLACK_BOT_CHANNEL_URL: ${{ vars.SLACK_BOT_CHANNEL_URL_STAGING }}
      SLACK_WALLET_WATCHER_URL: ${{ vars.SLACK_WALLET_WATCHER_URL_STAGING }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i -g yarn
      - run: npm i -g serverless

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install awscli --upgrade

      - uses: actions/checkout@v3
      - run: |
          yarn
          yarn deploy:staging
